---
- name: Set SELinux to Permissive
  become: yes
  selinux:
    policy: targeted
    state: permissive

- name: Disable Swap
  become: yes
  command: swapoff --all
  ignore_errors: yes

- name: Remove swapfile from /etc/fstab
  become: yes
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Copy Kubernetes Repo File
  become: yes
  copy:
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644

- name: Install Kubernetes
  become: yes
  dnf: 
    name:
      - "{{ kubeletversion }}"
      - "{{ kubectlversion }}"
      - "{{ kubeadmversion }}"
    state: installed

- name: Lock Kubelet, Kubectl and Kubeadm Versions
  become: yes
  shell: dnf versionlock kubelet kubeadm kubectl

- name: Copy k8s.conf
  become: yes
  copy:
    src: files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0644

- name: Create .kube directory
  file:
    path: "/home/{{ username }}/.kube"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700

- name: Enable and Start Kubelet
  become: yes
  service:
    name: "kubelet"
    enabled: yes
    state: started
