---
- name: Set SELinux to Permissive
  become: yes
  selinux:
    policy: targeted
    state: permissive

- name: Disable Swap
  become: yes
  command: swapoff --all
  ignore_errors: yes

- name: Remove swapfile from /etc/fstab
  become: yes
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Copy Kubernetes Repo File
  become: yes
  copy:
    src: files/kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644

- name: Install Kubernetes
  become: yes
  dnf:
    disable_excludes: kubernetes
    name:
      - "{{ kubeletversion }}"
      - "{{ kubectlversion }}"
      - "{{ kubeadmversion }}"
    state: installed

- name: Lock Kubelet, Kubectl and Kubeadm Versions
  become: yes
  shell: dnf versionlock kubelet kubeadm kubectl

- name: Copy sysctl k8s.conf
  become: yes
  copy:
    src: files/k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    owner: root
    group: root
    mode: 0644
  
- name: Copy modules load k8s.conf
  become: yes
  copy:
    src: files/modules_k8s.conf
    dest: /etc/modules-load.d/k8s.conf
    owner: root
    group: root
    mode: 0644

- name: Create crio.conf.d directory
  become: yes
  file:
    path: /etc/crio/crio.conf.d
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Copy cgroup driver
  become: yes
  copy:
    src: files/02-cgroup-manager.conf
    dest: /etc/crio/crio.conf.d/02-cgroup-manager.conf
    owner: root
    group: root
    mode: 0644

- name: Load settings  from  all system configuration files
  become: yes
  command: sysctl --system

- name: modprobe br_netfilter
  become: yes
  command: modprobe br_netfilter

# https://github.com/kubernetes/kubeadm/issues/312
- name: Set IP tables
  become: yes
  command: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables

- name: Create .kube directory
  file:
    path: "/home/{{ username }}/.kube"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0700

- name: Enable and Start Kubelet
  become: yes
  service:
    name: "kubelet"
    enabled: yes
    state: started
