---
- name: Set up libcontainer repo
  become: yes
  shell: curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ crioosvalue }}/devel:kubic:libcontainers:stable.repo

- name: Set up libcontainer cri-o repo
  become: yes
  shell: curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:{{ crioversion }}.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ crioversion }}/{{ crioosvalue }}/devel:kubic:libcontainers:stable:cri-o:{{ crioversion }}.repo

- name: Install Cri-O 
  become: yes
<<<<<<< HEAD
  shell: dnf install cri-o
=======
  shell: dnf install -y cri-o

- name: Force systemd to reread configs
  become: yes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start cri-o
  become: yes
  service:
    name: "crio"
    enabled: yes
    state: started
>>>>>>> b3a4cf9... Add support for Cri-O as the CRI and podman as the CE

# There is an issue with the cri-o installation where files are
# added that later conflict with the calico CIDR. Per the issue
# below, removing these files after install allows the correct
# settings to be configured later
# https://github.com/cri-o/cri-o/issues/2411#issuecomment-540006558
<<<<<<< HEAD
=======
# FOLLOW UP: This doesn't seem to work consistently. You may need to
# update the 100-crio-bridge.conf file to include the expected calico
# CIDR, i.e. 192.168.0.0/16 - see example in 'files' folder
>>>>>>> b3a4cf9... Add support for Cri-O as the CRI and podman as the CE
- name: Delete cri-o bridge file
  become: yes
  file:
    state: absent
    path: /etc/cni/net.d/100-crio-bridge.conf

- name: Delete cri-o loopback file
  become: yes
  file:
    state: absent
<<<<<<< HEAD
    path: /etc/cni/net.d/200-loopback.conf

- name: Force systemd to reread configs
  become: yes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start cri-o
  become: yes
  service:
    name: "crio"
    enabled: yes
    state: started
=======
    path: /etc/cni/net.d/200-loopback.conf
>>>>>>> b3a4cf9... Add support for Cri-O as the CRI and podman as the CE
