---
- name: Ensure EPEL is enabled 
  become: yes
  dnf: 
    name: epel-release 
    enablerepo: extras
    state: present 

- name: Install Extra Packages
  become: yes
  dnf: 
    name: 
      - golang
      - git
      - net-tools
      - bind-utils
    state: latest

- name: Install DNF Versionlock
  become: yes
  shell: dnf -y install 'dnf-command(versionlock)'

- name: Disable SELinux
  become: yes
  shell: setenforce 0

- name: Disable and Stop Firewalld
  become: yes
  service:
    name: "firewalld"
    enabled: no
    state: stopped

- name: Add hostname to /etc/hotss
  become: yes
  shell: echo "{{ kubemasterip }} {{ hostname }}" >> /etc/hosts
