---
- name: Run kubeadm init with Weave Overlay
  become: yes
  command: kubeadm init --apiserver-advertise-address={{ kubemasterip }}
  args:
    creates: /etc/.kubeadminit
  when: overlay == 'weave'

- name: Run kubeadm init with Calico Overlay
  become: yes
  command: kubeadm init --pod-network-cidr={{ kubecidr }}
  args:
    creates: /etc/.kubeadminit
  when: overlay == 'calico'

- name: Block kubeadm init
  become: yes
  command: touch /etc/.kubeadminit

- name: Copy Kubeconfig To Home
  become: yes
  command: cp /etc/kubernetes/admin.conf /home/{{ username }}/.kube/config

- name: Setup Config Permissions
  become: yes
  file:
    path: "/home/{{ username }}/.kube/config"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Get Kubectl Version
  shell: kubectl version | base64 | tr -d '\n'
  register: kubectl_version

- name: Taint Master Node
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-
